// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zneejoqfgrqzvutkituy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpuZWVqb3FmZ3JxenZ1dGtpdHV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM1MTYyNjcsImV4cCI6MjA0OTA5MjI2N30.ZXTodu9881OiUnJaDVjNNIYPO9IuEhzUJpNUI_XOYBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);